FROM ros:noetic-robot

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install -y \ 
    build-essential \ 
    nano \ 
    iputils-ping \ 
    net-tools \ 
    curl \ 
    lsb-release \ 
    git \ 
    python3-rosdep \ 
    python3-catkin-tools \ 
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \ 
    ros-noetic-roslint \ 
    ros-noetic-industrial-msgs \ 
    ros-noetic-industrial-robot-client \ 
    ros-noetic-simple-message \ 
    ros-noetic-rviz \ 
    ros-noetic-moveit \ 
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true && rosdep update

WORKDIR /root/catkin_ws

RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc

CMD ["bash"]
