services:
  roscore:
    build:
      context: .
      args:
        - USER_UID=${MY_UID:-1000}
        - USER_GID=${MY_GID:-1000}
    image: thesis:latest
    container_name: roscore
    network_mode: host
    restart: "no"
    entrypoint: /bin/bash
    environment:
      ROS_IP: 127.0.0.1
      ROS_DOMAIN_ID: 0
      ROS_MASTER_URI: http://localhost:11311
      ROS_LOG_DIR: /tmp/ros_logs
    command: -c "source /opt/ros/noetic/setup.bash && roscore"

  motoman_controller:
    image: thesis:latest
    container_name: motoman_controller
    network_mode: host
    restart: "no"
    entrypoint: [ "/bin/bash", "-c" ]
    depends_on:
      - roscore
    user: "${MY_UID:-1000}:${MY_GID:-1000}"
    volumes:
      - ./motoman_driver:/home/rosuser/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri:rw
    environment:
      ROS_IP: 127.0.0.1
      ROS_DOMAIN_ID: 0
      ROS1_EOL_DISABLE: 1
      ROS_MASTER_URI: http://localhost:11311
      ROS_LOG_DIR: /tmp/ros_logs
      DISPLAY: ${DISPLAY:-:0}
    working_dir: /home/rosuser/catkin_ws
    # command: -c "echo 'Motoman Controller Ready'; sleep infinity"
    command: "./run_motomini.sh"
  tool_manager:
    image: thesis:latest
    container_name: tool_manager
    network_mode: host
    depends_on:
      - motoman_controller
    user: "${MY_UID:-1000}:${MY_GID:-1000}"
    volumes:
      - ./motoman_driver:/home/rosuser/catkin_ws
    working_dir: /home/rosuser/catkin_ws
    entrypoint: [ "/bin/bash", "-c" ]
    command: "source devel/setup.bash && python3 ./tool_service.py"
  ros1_bridge:
    image: thesis:latest
    container_name: ros1_bridge
    network_mode: host
    restart: "no"
    entrypoint: /bin/bash
    depends_on:
      - roscore
    user: "${MY_UID:-1000}:${MY_GID:-1000}"
    volumes:
      - ./ros_bridge:/home/rosuser/ros2_ws
      - ./motoman_driver:/home/rosuser/catkin_ws
      - /dev/shm:/dev/shm
    environment:
      ROS_IP: 127.0.0.1
      ROS_MASTER_URI: http://localhost:11311
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      ROS_LOG_DIR: /tmp/ros_logs
      FASTRTPS_DEFAULT_PROFILES_FILE: /home/rosuser/ros2_ws/fastdds_udp.xml
    working_dir: /home/rosuser/ros2_ws
    command: >
      -c " ./run_parameter_bridge.sh && echo 'Starting ROS1-ROS2 Bridge...' && tail -f /dev/null "

  gandtry_driver:
    image: thesis:latest
    container_name: gandtry_driver
    network_mode: host
    restart: "no"
    entrypoint: [ "/bin/bash", "-c" ]
    depends_on:
      - roscore
    user: "${MY_UID:-1000}:${MY_GID:-1000}"
    volumes:
      - ./ros_bridge:/home/rosuser/ros2_ws
      - /dev/shm:/dev/shm
    environment:
      ROS_IP: 127.0.0.1
      ROS_DOMAIN_ID: 0
      ROS1_EOL_DISABLE: 1
      ROS_MASTER_URI: http://localhost:11311
      ROS_LOG_DIR: /tmp/ros_logs
      DISPLAY: ${DISPLAY:-:0}
    working_dir: /home/rosuser/ros2_ws
    command: -c "echo 'test Controller Ready'; sleep infinity"
    # command: "./run_motomini.sh"
