controller_list:
  - name: arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []
  - name: hand
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      []